name: pytest

on:
  push:
    branches:
      - main

jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: python set up ${{ matrix.python-version }}
        uses: actions/setup-python@v1
      - name: install pytest
        run: pip3 install pytest
      - name: set PYTHONPATH
        env:
          PYTHONPATH=${{ github.workspace }}
        run: echo "PYTHONPATH=${PYTHONPATH}" >> $GITHUB_ENV
      - name: run pytest
        run: |
          pwd
          cd ${{ github.workspace }}
          pwd
          pytest tests

